Async comp builder
beatlabs/patron pull request #110
Opened 2019-11-24 15:57 UTC by drakos74

## Which problem is this PR solving?

Async Component Builder Pattern #54

## Short description of the changes

- introduced aync component builder
(following the suggestion in the issue, backwards compatibility has been broken)
p.s. If this is not acceptable, we can keep the 'New' method as the component constructor, and use another name for the builder constructor
- introduced iota for enum of Failure Strategies and a map for values ,
to make comparisons regarding this enum easier
- extended test scope to cover ALL failure scenarios / code paths
- refactor tests for async component, to make them more compact and readable
- re-used string templates for repeating log or error messages
- refactored error wrapping to use the simpler fmt.Errorf func
- adjusted the existing examples to use the builder

2019-11-28 06:02 UTC, mantzas requested changes

2019-11-28 06:02 UTC, mantzas commented on async/component.go
> +	if _, ok := failStrategyValues[fs]; ok {
As I understand it, we are using the map to check if we support the failurestrategy or if and invalid value has been passed in.
If that is the reason we should do a simple switch statement to see if the value is acceptable or not, and avoid having an map allocated

2019-11-28 08:12 UTC, drakos74 commented on async/component.go
> +func (cb *Builder) WithProcessor(proc ProcessorFunc) *Builder {
agreed , just followed the example in the issue. 
Will adjust

2019-11-28 08:17 UTC, drakos74 commented on async/component.go
> +var propSetMSG = "property '%s' set for '%s'"
yeap!

2019-11-28 08:24 UTC, drakos74 commented on async/component.go
> +var failureStrategyErrorMSG = "%s failed when executing failure strategy"
yeap!

2019-11-28 09:50 UTC, mantzas submitted a review, later dismissed

2019-12-27 12:27 UTC, moukoublen submitted a review, later dismissed

2020-01-02 09:42 UTC, moukoublen approved these changes

2020-01-02 16:09 UTC, mantzas approved these changes

2020-01-02 16:09 UTC, merged