WIP Replace errors.Wrap
beatlabs/patron pull request #125
Opened 2020-01-01 17:54 UTC by mantzas

## Which problem is this PR solving?

ThisPR closes #124

## Short description of the changes

Deleted errors package functions and replaced with fmt.Errorf

2020-01-02 11:00 UTC, drakos74 submitted a review, later dismissed

2020-01-03 12:51 UTC, fpapadopou requested changes

2020-01-03 12:51 UTC, fpapadopou commented on async/component.go
> +		err1 := msg.Nack()
How about `nackErr`instead of `err1`?

2020-01-03 13:26 UTC, fpapadopou submitted a review, later dismissed

2020-01-03 13:27 UTC, fpapadopou commented
@mantzas will you resolve conflicts? I can do it too, if you want

2020-01-03 13:28 UTC, mantzas commented
> @mantzas will you resolve conflicts? I can do it too, if you want

@fpapadopou that's the big fun... i am on it! Thanks

2020-01-03 13:39 UTC, fpapadopou requested changes

2020-01-03 13:39 UTC, fpapadopou commented on async/component_test.go
> +<<<<<<< HEAD
Oops

2020-01-03 13:39 UTC, mantzas commented on async/component_test.go
> +<<<<<<< HEAD
Seen it... on it

2020-01-03 13:43 UTC, fpapadopou approved these changes

2020-01-06 14:04 UTC, drakos74 approved these changes

2020-01-06 19:24 UTC, merged