WIP Issue #71 Support Kafka consumer group with multiple topics
beatlabs/patron pull request #134
Opened 2020-01-12 22:12 UTC by moukoublen

## Which problem is this PR solving?

## Short description of the changes

2020-01-15 11:56 UTC, drakos74 submitted a review, later dismissed

2020-01-16 19:39 UTC, mantzas requested changes

2020-01-16 19:39 UTC, mantzas commented on async/amqp/amqp.go
> +	queue   string
maybe name this also source like the getter. Queue is more message broker specific, Kafka has topics,..

2020-01-16 19:47 UTC, mantzas submitted a review, later dismissed

2020-01-21 13:30 UTC, drakos74 submitted a review, later dismissed

2020-01-28 16:23 UTC, mantzas approved these changes

2020-02-03 08:29 UTC, drakos74 approved these changes

2020-02-04 11:22 UTC, sotirispl approved these changes

2020-02-05 19:27 UTC, merged