Get access to message payload
beatlabs/patron pull request #211
Opened 2020-05-13 16:01 UTC by teivah

https://github.com/beatlabs/patron/issues/210

2020-05-13 16:02 UTC, teivah commented on component/async/kafka/kafka.go
> +func (m *message) Source() string {
I just swapped Source() and Nack() so that we have the same order in all the implem & the interface

2020-05-13 16:07 UTC, drakos74 submitted a review, later dismissed
nice! I always had this urge to make this change. Happy that the use-case came up :)

2020-05-13 16:11 UTC, mantzas requested changes

2020-05-13 16:11 UTC, mantzas commented on component/async/component_test.go
> +func (mm *mockMessage) Payload() []byte {
Is there a test to add this as a check?

2020-05-14 06:13 UTC, mantzas approved these changes

2020-05-14 12:13 UTC, drakos74 approved these changes

2020-05-14 12:37 UTC, fpapadopou approved these changes

2020-05-14 12:37 UTC, fpapadopou commented
🚢

2020-05-14 13:00 UTC, merged