Issue #204 - Redis Get response in case of missing value
beatlabs/patron pull request #238
Opened 2020-07-21 17:05 UTC by christgf

Signed-off-by: George Christou <christgf@gmail.com>
## Which problem is this PR solving?

Resolves #204 - Redis Get response in case of missing value

## Short description of the changes

When returning results from Redis, an empty cache key is handled as an error, which is inconsistent with the caching API interface. The change ensures cache misses don't result in errors, as proposed.
Please note there's currently no test fixture for the Redis cache implementation.

2020-07-21 17:12 UTC, mantzas requested changes

2020-07-21 17:12 UTC, mantzas commented on cache/redis/redis.go
> +	if err == nil {
I would suggest to use the usual pattern and check first for the err != nil. Inside you check specifically for redis.Nil.
the happy path should be the last statement...

2020-07-21 17:29 UTC, mantzas approved these changes
Nice, thanks very much for the contribution.

2020-07-21 17:45 UTC, tpaschalis requested changes
Thank you for taking the time to open your first PR in Patron!

It looks good, just one remark; I think that we can remove [this](https://github.com/beatlabs/patron/blob/dcb169177d3637d677690416f0b75a8e7c7aee92/client/redis/redis.go#L25) `const Nil = redis.Nil`  as well.

It was used to export the `redis.Nil` error so that the end-user could implement the cache miss check herself, but this is no longer necessary!

2020-07-21 18:18 UTC, christgf commented
> Thank you for taking the time to open your first PR in Patron!
> 
> It looks good, just one remark; I think that we can remove [this](https://github.com/beatlabs/patron/blob/dcb169177d3637d677690416f0b75a8e7c7aee92/client/redis/redis.go#L25) `const Nil = redis.Nil` as well.
> 
> It was used to export the `redis.Nil` error so that the end-user could implement the cache miss check herself, but this is no longer necessary!

Actually @tpaschalis, it seems that this still serves its original purpose, and removing it would require we import redis/v7 in the Redis cache implementation (which is where the redis.Nil check is needed).
I may be missing your point altogether?

2020-07-21 18:33 UTC, tpaschalis commented
> Actually @tpaschalis, it seems that this still serves its original purpose, and removing it would require we import redis/v7 in the Redis cache implementation (which is where the redis.Nil check is needed).
> I may be missing your point altogether?

On the other hand, you're right, let's keep the imports all in one place!

2020-07-21 18:33 UTC, tpaschalis approved these changes
LGTM!

2020-07-22 15:28 UTC, drakos74 approved these changes
nice!!!

2020-07-22 15:44 UTC, merged