Kafka consumer option: new session callback
beatlabs/patron pull request #468
Opened 2022-02-18 15:33 UTC by teivah

## Which problem is this PR solving?

https://github.com/beatlabs/patron/issues/467

## Short description of the changes

Add a new option that set a specific callback.

2022-02-18 15:53 UTC, mantzas requested changes

2022-02-18 15:53 UTC, mantzas commented on component/kafka/group/option_test.go
> +				assert.NoError(t, err)
there is an assertion missing about setting the callback?

2022-02-18 16:38 UTC, teivah commented on component/kafka/group/option_test.go
> +				assert.NoError(t, err)
Thanks 👍 I've added the assertions on the nullity.

2022-02-18 16:38 UTC, mantzas approved these changes

2022-02-21 13:20 UTC, gmaz42 approved these changes

2022-02-21 13:26 UTC, merged