Split tracing agent address into host & port
beatlabs/patron pull request #60
Opened 2019-06-04 16:17 UTC by sotirispl

Signed-off-by: Sotiris Poulias <str.poulias@gmail.com>

## Which problem is this PR solving?

Solves #59 

## Short description of the changes

Splitting env var of jaeger agent address into host and port, helps the dynamic configuration under k8s management.

2019-06-05 07:54 UTC, mantzas requested changes

2019-06-05 07:54 UTC, mantzas commented on README.md
> +  - agent port `6831` with `PATRON_JAEGER_AGENT_POST`
`PATRON_JAEGER_AGENT_PORT`

2019-06-05 08:12 UTC, mantzas approved these changes

2019-06-06 13:11 UTC, cpapidas approved these changes

2019-06-06 13:12 UTC, merged