Service refactoring
beatlabs/patron pull request #604
Opened 2023-01-04 15:35 UTC by mantzas

## Which problem is this PR solving?

## Short description of the changes

2023-01-27 14:49 UTC, xenosdio submitted a review, later dismissed

2023-01-27 21:25 UTC, pkritiotis requested changes
Looks good, just a tiny comment

2023-01-27 21:25 UTC, pkritiotis commented on component/http/component.go
> +	portVal := int64(defaultPort)
Do we need an `int64` here?

2023-01-27 21:25 UTC, pkritiotis commented on component/http/component.go
> +	portVal := int64(defaultPort)
Also it seems that this line is redundant since this variable is then assigned to the parsed value of the env var

2023-01-27 21:25 UTC, pkritiotis commented on component/http/v2/component.go
> +	portVal := int64(defaultPort)
Same case here

2023-01-28 10:38 UTC, mantzas commented on component/http/component.go
> +	portVal := int64(defaultPort)
good catch!

2023-01-28 10:38 UTC, mantzas commented on component/http/v2/component.go
> +	portVal := int64(defaultPort)
good catch!

2023-01-31 08:04 UTC, pkritiotis approved these changes

2023-01-31 08:56 UTC, xenosdio approved these changes

2023-01-31 21:17 UTC, merged