Added generation of a .gitignore
beatlabs/patron pull request #90
Opened 2019-10-01 08:15 UTC by azarakovskiy

## Which problem is this PR solving?

New projects normally require a `.gitignore` file to avoid committing local project files or test output. This would be nice if patron generated it OOB.

## Short description of the changes

- Added a template `.gitignore`
- Copy a template to a generated project

2019-10-01 08:20 UTC, mantzas requested changes

2019-10-01 08:20 UTC, mantzas commented on cmd/patron/main.go
> +
you can just `return err` here

2019-10-01 09:55 UTC, azarakovskiy commented on cmd/patron/main.go
> +
Done

2019-10-01 09:56 UTC, azarakovskiy commented
PS: not sure why github closed the initial PR

2019-10-01 09:57 UTC, mantzas approved these changes

2019-10-07 10:46 UTC, azarakovskiy commented
@cpapidas @sotirispl

2019-10-07 13:45 UTC, sotirispl approved these changes

2019-10-07 14:17 UTC, cpapidas approved these changes
Good job 👍

2019-10-08 07:44 UTC, merged